spring.application.name=springAI
spring.ai.mcp.server.protocol=streamable

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:~/ticket-request-db
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=gemma4
spring.ai.ollama.embedding.model=embeddinggemma

#spring.ai.chat.memory.repository.jdbc.initialize-schema=always

spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.collection-name=cricket_history

spring.ai.mcp.server.request-timeout=180s

spring.docker.compose.stop.command=down

#spring.ai.mcp.server.name=spring-ai-mcp-server
#logging.level.root=off
#spring.main.banner-mode=off